# Based on: https://github.com/arthurlopes/ctbench/blob/master/FlowTracker/dudect%20examples/aes32/in.xml
functions:
  - rijndaelKeySetupEnc
  # - rijndaelKeySetupDec => cannot unroll loops
  - rijndaelEncrypt
  # - rijndaelDecrypt => not used
sources:
  - main1.c
  - main2.c
  - main3.c
libs:
  - dut_aes32.c
  - rijndael-alg-fst.c
  - random.c
cache:
  - --I1=16384;4;1024
  - --D1=16384;4;1024
  - --LL=16384;4;1024
