# Based on: https://github.com/arthurlopes/ctbench/blob/master/FlowTracker/BearSSL/hash/md5/in.xml
functions:
  - br_md5_round
sources:
  - main1.c
  - main2.c
libs:
  - dut_md5.c
  - md5.c
  - enc32le.c
  - dec32le.c
  - random.c
cache:
  - --I1=16384;4;1024
  - --D1=16384;4;1024
  - --LL=16384;4;1024
